main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('profile/', views.my_profile, name='my_profile'),
    path('profile/<username>/', views.profile, name='user_profile'),
]

posties/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("v1/", views.v1, name="view1"),
]

posties/posties/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

posties/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as v
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include("django.contrib.auth.urls")),
    path("register/", v.register, name="register"),
    path("accounts/", include("allauth.urls")),
    path('all_events/', v.all_events, name='all_events'),
    path('add_event/', v.add_event, name='add_event'),
    path('remove/', v.remove, name='remove'),
    path('edit/', v.edit, name='edit'),
    path('help', v.help, name="help"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
 
# Create your models here.
class Event(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300,null=True,blank=True)
    start = models.DateTimeField(null=True,blank=True)
    end = models.DateTimeField(null=True,blank=True)
    username = models.CharField(max_length=300)
    log_date = models.DateTimeField("date logged")
 
    class Meta:  
        db_table = "tblevents"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_pic.jpg', upload_to='profile_images')
    bio = models.TextField(default="This user has no bio.")

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 200 or img.width > 200: # Downsizes large images to improve performance
            new_img = (200, 200)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def clean_username(self): # Checks if the inputted username is already in use and allows or denies the account creation appropriately
        username = self.cleaned_data['username']
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(u'Username "%s" is already in use.' % username)

class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterForm
from django.http import JsonResponse
from .models import Event, Profile
from dateutil.parser import parse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UpdateProfileForm

# Create your views here.
def home(response):
    all_events = Event.objects.all()
    context = {
        "events": all_events,
    }
    return render(response, "main/home.html")

def all_events(request):
    all_events = Event.objects.all()
    out = []
    for event in all_events:
        out.append({
            'title': event.name,
            'id': event.id,
            'start': event.start.strftime("%m/%d/%Y, %H:%M:%S"),
            'end': event.end.strftime("%m/%d/%Y, %H:%M:%S"),
            'username': event.username,
            'log_date': event.log_date.strftime("%#m/%#d/%Y, %#I:%M:%S %p"), # The formatting prevents the date format from changing after a post edit
        })
    return JsonResponse(out, safe=False)
 
def add_event(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    username = request.GET.get("username", None)
    log_date = parse(request.GET.get("log_date", None)) # Parse makes sure the date is of the right format, it cannot be passed otherwise
    event = Event(name=str(title), start=start, end=end, username=str(username), log_date=log_date)
    event.save()
    data = {}
    return JsonResponse(data)

def edit(request):
    id = request.GET.get("id", None)
    event = Event.objects.get(id=id)
    title = request.GET.get("title", None)
    username = request.GET.get("username", None)
    if (username == event.username):
        event.name = str(title)
        event.save()
    data = {}
    return JsonResponse(data)

def remove(request):
    id = request.GET.get("id", None)
    event = Event.objects.get(id=id)
    username = request.GET.get("username", None)
    if (username == event.username):
        event.delete()
    data = {}
    return JsonResponse(data)

def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    else:
        form = RegisterForm()
    return render(response, "register/register.html", {"form":form})

def help(response):
    return render(response, "main/help.html")

@login_required
def my_profile(request):
    if request.method == 'POST':
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile has been updated successfully.')
        else:
            messages.error(request, 'An error occured. Your profile has not been updated.')
        return redirect(to='my_profile')
    else:
        profile_form = UpdateProfileForm(instance=request.user.profile)
    return render(request, 'main/my_profile.html', {'profile_form': profile_form})

def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = Profile.objects.get(user=user)
    context = {
        'profile': profile,
    }
    return render(request, 'main/profile.html', context)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        {% block extra_head_content %}
        {% endblock %}
    </head>

    <body>
        <div class="body-content">
            {% block content %}
            {% endblock %}

            <hr>
            <footer>
                &copy; 2024 Posties
            </footer>
        </div>
    </body>
</html>

main/templates/main/help.html
{% extends "main/base.html" %}

{% block title %}Posties - Help{% endblock %}

{% block content %}
    <center>
        <h1>HELP</h1>
        <br>
        <h2>Welcome to Posties!</h2>
        <p style="font-size: 20px">
            Posties is a unique social media application where users can interact through putting "sticky notes" onto a virtual board.<br>
            To create posts, you must first make an account and log in.<br><br>

            How to use the site:<br>
            Create a post by clicking on any empty space within a grid cell (login required).<br>
            Edit or delete a post by clicking on a post you made (login required).<br>
            View a user's profile by clicking on a post that is not your own.<br>
        </p>
        <button onclick="location.href=href='/'" class="btn btn-primary">Home</button>
    </center>
{% endblock %}

main/templates/main/home.html
{% extends "main/base.html" %}

{% block title %}Posties - Home{% endblock %}

{% block extra_head_content %}
    <!-- Required content to use a calendar, FullCalendar, as a base -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
    
    <!-- Adds the eventRightclick function -->
    {% load static %}
    <script src="{% static 'main/fullcalendar-rightclick.js' %}"></script>

    {{ request.user.username | json_script:"username" }}
{% endblock %}

{% block content %}
    <!-- Prevents the successful login message from appearing -->
    {% if messages %} 
        {% for message in messages %}
        {% endfor %}
    {% endif %}

    <center><h1>POSTIES</h1></center>

    <!-- Navigation Buttons -->
    <button type="button" class="btn btn-light" id="prev">
        <b>&lt;</b>
    </button>
    <button type="button" class="btn btn-light" id="next">
        <b>&gt;</b>
    </button>
    <script>
        // The buttons skip 2 grids at once to circumvent a problem w/ using a calendar base that causes posts at the beginning/end of the grid to appear on the previous/next grid
        $("#next").click(function() {
            $("#calendar").fullCalendar("next");
            $("#calendar").fullCalendar("next");
        });
        $("#prev").click(function() {
            $("#calendar").fullCalendar("prev");
            $("#calendar").fullCalendar("prev");
        });
    </script>
    {% if user.is_authenticated %}
        <button onclick="location.href=href='/logout'" class="btn btn-danger nav-button-right">Logout</button>
        <button onclick="location.href=href='/profile'" class="btn btn-warning nav-button">Profile</button>
    {% else %}
        <button onclick="location.href=href='/login'" class="btn btn-success nav-button-right">Login</button>
    {% endif %}
    <button onclick="location.href=href='/help'" class="btn btn-info nav-button" style="margin-bottom: 5px;">Help</button>

    <script>
        const username = JSON.parse(document.getElementById('username').textContent);
        var isAuthenticated = '{{request.user.is_authenticated}}' === 'True';

        $(document).ready(function () {
            calendar = $('#calendar').fullCalendar({ // If signed in, a "calendar"/series of grids is displayed that allows the user to create posts in grid cells
                header: false,
                events: '/all_events', // events = posts
                selectable: true,
                columnHeader: false,
                allDayDefault: true, // Makes the calendar's event times not appear on posts
                eventOrder: '', // Makes posts ordered by recency
                eventTextColor: 'black',
                eventBorderColor: 'black',
                contentHeight: '9999', // Makes posts have dynamic height
                hiddenDays: [0], // Removes a column to make the grid a 6x6
                selectAllow: function(selectInfo) { // Prevents selecting more than one "day"/grid cell at a time, making "long-posting" impossible
                    const oneDay = 86400000; // Number of milliseconds in a day
                    var startDay = selectInfo.start;
                    var endDay = selectInfo.end - oneDay; // selectInfo.end always starts one day past selectInfo.start
                    if (startDay == endDay) {
                        return true;
                    }
                    else {
                        return false;
                    }
                },
                select: function (start, end, allDay) { // Allows the user to create posts
                    if (isAuthenticated) {
                        var charLimit = 50;
                        var title = prompt("Enter message (" + charLimit + " char limit):"); // title = post message
                        if (title.length > charLimit) {
                            title = title.substr(0, charLimit);
                        }
                        if (title) {
                            var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss");
                            var end = $.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss");
                            const log_date = new Date().toLocaleString();
                            $.ajax({
                                type: "GET",
                                url: '/add_event',
                                data: {'title': title + "\n\n" + username + "\n" + log_date, 'start': start, 'end': end, 'username': username, 'log_date': log_date}, // Adds extra info to title for display purposes only
                                dataType: "json",
                                success: function (data) {
                                    calendar.fullCalendar('refetchEvents');
                                },
                                error: function (data) {
                                    alert('Error: Please try again');
                                }
                            });
                        }
                    }
                },
                eventClick: function (event) { // Allows the user to manage their own posts and view other users' profiles
                    if (username == event.username) {
                        eventID = event.id;
                        eventLogDate = event.log_date;
                        $("#manageModal").modal("show");
                    }
                    else {
                        eventUsername = event.username;
                        $("#profileModal").modal("show");
                    }
                },
            });
        });
    </script>

    <!-- Post Management Modal -->
    <div class="modal fade" id="manageModal" tabindex="-1" aria-labelledby="manageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="manageModalLabel">What would you like to do?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal" onclick="editPost()">Edit Post</button>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="deletePost()">Delete Post</button>
                </div>
            </div>
        </div>
    </div>
    <!-- View Profile Modal -->
    <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="profileModalLabel">Continue to profile?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <button type="button" class="btn btn-warning" data-bs-dismiss="modal" onclick="location.href=href='/profile/' + eventUsername">View Profile</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function editPost() {
            var charLimit = 50;
            var title = prompt("Enter an updated message (" + charLimit + " char limit):"); // title = post message
            if (title.length > charLimit) {
                title = title.substr(0, charLimit);
            }
            if (title) {
                $.ajax({
                    type: "GET",
                    url: '/edit',
                    data: {'id': eventID, 'title': title + "\n\n" + username  + "\n" + eventLogDate + " (Edited)", 'username': username}, // Adds extra info to title for display purposes only
                    dataType: "json",
                    success: function (data) {
                        calendar.fullCalendar('refetchEvents');
                    },
                    error: function (data) {
                        alert('Error: Please try again');
                    }
                });
            }
        }
        function deletePost() {
            if (confirm("Are you sure you want to delete this post?")) {
                $.ajax({
                    type: "GET",
                    url: '/remove',
                    data: {'id': eventID, 'username': username},
                    dataType: "json",
                    success: function (data) {
                        calendar.fullCalendar('refetchEvents');
                    },
                    error: function (data) {
                        alert('Error: Please try again');
                    }
                });
            }
        }
    </script>
    
    <div class="col-md-12">
        <div id='calendar'></div> <!-- calendar = series of grids where posts can be made in grid cells -->
    </div>
{% endblock %}

main/templates/main/my_profile.html
{% extends "main/base.html" %}

{% block title %}Posties - Your Profile{% endblock %}

{% block content %}
    <center>
        <h1 class="profile-header">{{ user.username }}</h1>
        <br>
        <button onclick="location.href=href='/'" class="btn btn-primary nav-button-right">Home</button>
        <div class="pfp-div">
            <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }}" alt="Your profile picture"/>
        </div>
        <br>
        {% if user_form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <div id="form_errors">
                    {% for key, value in user_form.errors.items %}
                        <strong>{{ value }}</strong>
                    {% endfor %}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-5">
                <div class="form-group"><label for="id_avatar" class="small mb-1">Change Avatar:</label> {{ profile_form.avatar }} </div>
            </div>
            <div class="col-md-5" style="text-align:left;">
                <label for="id_bio" class="small mb-1">Bio:</label>
                {{ profile_form.bio }}
            </div>
            <br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
            <button type="reset" class="btn btn-dark btn-lg">Reset</button>
        </form>
        {% for message in messages %}
            <br>
            {{ message }}
        {% endfor %}
    </center>
{% endblock %}

main/templates/main/profile.html
{% extends "main/base.html" %}

{% block title %}Posties - {{ profile.user }}'s Profile{% endblock %}

{% block content %}
    <center>
        <h1 class="profile-header">{{ profile.user }}</h1>
        <br>
        <button onclick="location.href=href='/'" class="btn btn-primary nav-button-right">Home</button>
        <div class="pfp-div">
            <img class="rounded-circle account-img" src="{{ profile.avatar.url }}" alt="This user's profile picture"/>
        </div>
        <br>
        <div id="bio" style="background-color: white; border-style: solid; border-width: 1px; padding: 10px; width: 500px;">
            {{ profile.bio }}
        </div>
    </center>
{% endblock %}

main/templates/register/register.html
{% extends "main/base.html" %}

{% block title %}Posties - Account Registration{% endblock %}

{% block content %}
        {% if user.is_authenticated %}
            <center>
                <h1 class="signed-in-header">You are already signed in.</h1>
                <button onclick="location.href=href='/'" class="btn btn-primary">Home</button>
            </center>
        {% else %}
            <center><h1 style="width: 500px;">REGISTER AN ACCOUNT</h1></center>
            <br>
            <div class="d-flex justify-content-center">
                <form method="POST" class="form-group">
                    {% csrf_token %}
                    {{form}}
                    <button type="submit" class="btn btn-success">Register</button>
                </form>
            </div>
        {% endif %}
{% endblock %}